services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    image: bezdefectov:latest
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./logs/fastapi:/app/logs
      - ./media:/media
      - ./static:/static
    command: uvicorn src:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - backend_net

  db:
    image: postgres:16
    user: "999:999"
    env_file: .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - backend_net
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    env_file:
      - .env.prod
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
    networks:
      - backend_net
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env.prod
    volumes:
      - ./logs/nginx:/var/log/nginx
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
      - ./static:/static:ro
      - ./media:/media:ro
    networks:
      - backend_net

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
    entrypoint:
      - certbot
      - certonly
      - --webroot
      - -w
      - /var/www/certbot
      - --email
      - admin@gmail.com
      - --agree-tos
      - --no-eff-email
      - --non-interactive
      - --force-renewal
      - -d
      - migom.shop
      - -d
      - api.migom.shop
    networks:
      - backend_net



volumes:
  pgdata:
  redis_data:
  certbot_www:
  certbot_etc:

networks:
  backend_net:
    driver: bridge
