services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    image: bezdefectov:latest
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./logs/fastapi:/app/logs
      - ./media:/media
      - ./static:/static
    command: uvicorn src:app --reload --host 0.0.0.0 --port 8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/ || exit 1" ]
      interval: 5s
      retries: 5
    ports:
      - "8000:8000"
    networks:
      - backend_net

  db:
    image: postgres:16
    user: "999:999"
    env_file: .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      retries: 5
    networks:
      - backend_net
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
    networks:
      - backend_net
    restart: always

  nginx:
    build: ./infra/nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
    depends_on:
      - backend
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
      - ./static:/static:ro
      - ./media:/media:ro
    restart: unless-stopped
    networks:
      - backend_net

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
    entrypoint:
      - certbot
      - certonly
      - --webroot
      - -w
      - /var/www/certbot
      - --email
      - admin@gmail.com
      - --agree-tos
      - --no-eff-email
      - --non-interactive
      - --force-renewal
      - -d
      - migom.shop
      - -d
      - api.migom.shop
    networks:
      - backend_net

volumes:
  pgdata:
  redis_data:
  certbot_www:
  certbot_etc:

networks:
  backend_net:
    driver: bridge
